export const forestAudio = new Audio('../assets/sounds/Floresta.mp3')
export const rainAudio = new Audio('../assets/sounds/Chuva.mp3')
export const fireAudio = new Audio('../assets/sounds/Lareira.mp3')
export const coffeeAudio = new Audio('../assets/sounds/Cafeteria.mp3')
export const buttonPress = new Audio('../assets/sounds/ButtonPress.mp3')

export const rainButton = document.getElementById("rain")
export const fireButton = document.getElementById("fire")
export const coffeeButton = document.getElementById("coffee")
export const forestButton = document.getElementById("forest")
export const playButton = document.getElementById("play")
export const pauseButton = document.getElementById("pause")
export const stopButton = document.getElementById("stop")
export const plusButton = document.getElementById("plus")
export const minusButton = document.getElementById("minus")
export const setButton = document.getElementById("set")

export const minutes = document.getElementById('minutes')
export const seconds = document.getElementById('seconds')